### ISSUE TITLE
Provide a way to disallow fallback to local compilation

### ISSUE THREAD

**Issue by acmorrow** [icecc/icecream#551] opened 2020-07-23 18:07 UTC
If remote compilation fails, icecream will fall back to local compilation.

If a coding error which causes remote compilation to fail doesn't also cause local compilation to fail, and if the coding error is in a header used by many translation units, this can cause a very large number of jobs to be queued to run locally. This happened, for instance, in a header where a tautology had been wrapped in a macro. Apparently, GCC's -Wtautological-compare can't catch this particular error when it is inside the macro in question, but with local preprocessing and remote compilation, GCC sees the expanded version of the macro and issues an error, resulting in fallback to successful local compilation.

The user facing effect is that the build appears to be very slow, but the user never sees the error, since the local compilation succeeds.

I would like to require that all source files in the project succeed in remote compilation. Disallowing local compilation entirely and simply failing the build if remote compilation fails seems like a good way to enforce that. At the very least, it will help us shake out any other subtle errors that are causing particular jobs to silently fall back to local, after consuming cluster resources without any chance of succeeding.

If there is already a way to do this, that would be great, but a quick look through the documentation did not reveal anything.

**Comment by llunak** [comment] 2020-07-24 19:33
> If a coding error which causes remote compilation to fail doesn't also cause local compilation to fail, and if the coding error is in a header used by many translation units, this can cause a very large number of jobs to be queued to run locally. This happened, for instance, in a header where a tautology had been wrapped in a macro. Apparently, GCC's -Wtautological-compare can't catch this particular error when it is inside the macro in question, but with local preprocessing and remote compilation, GCC sees the expanded version of the macro and issues an error, resulting in fallback to successful local compilation.

This should happen only with ICECC_REMOTE_CPP=0, which is not the default. Why do you use it?

**Comment by llunak** [comment] 2020-07-24 20:23
Or maybe you use -pedantic with GNU extensions enabled, in which case this is a duplicate of #537 .

**Comment by acmorrow** [comment] 2020-07-27 13:20
@llunak - No, not using `-pedantic` or GNU extensions. What we have found empirically is that with icecream 1.1, certain combinations of GCC and ccache versions fail to work correctly when using remote preprocessing. So if we detect the combination icecream 1.1, ccache, GCC, we set `ICECC_REMOTE_CPP=0` to work around it. Having done some more investigation, it looks like setting `ICECC_CARET_WORKAROUND=0` may achieve what we want here.

**Comment by llunak** [comment] 2020-07-27 14:28
If your problems involve a version that is 3 years old, I don't quite see how changing something in a new version would affect anything, especially given that just upgrading could very well avoid the problem. Moreover if you tweak things manually, it should be primarily your responsibility to check it works correctly. The default setup, as far as I can tell, works fine. I don't see a good reason to add more hacks to help with hacks, and I suggest first trying a more recent version rather than pilling on even ICECC_CARET_WORKAROUND=0.

**Closed by llunak** 2020-07-27 14:28 UTC
Labels: needinfo
