### ISSUE TITLE
scheduler: stop trying to give jobs to uncooperative clients

### ISSUE THREAD

**Issue by ec1oud** [icecc/icecream#143] opened 2016-03-02 08:10 UTC
I keep seeing messages like this

ICECC[2983] 09:08:16: no server found behind given hostname 10.-.-.-:10245
ICECC[2983] 09:08:16: got exception 2 (10.-.-.-) 

I don't really understand what it means, but can verify that machine is not listening on that port.

Why can't the scheduler just give up on that client until the problem is corrected?  Ideally with some way to warn the user on that machine too.

**Comment by HenryMiller1** [comment] 2016-04-07 16:22
This isn't easy - the scheduler cannot just give up on those clients - there might be firewall rules that allow some but not all users to get to that client.  Also, this error is entirely on the client side and doesn't get sent to the scheduler so the scheduler doesn't know that there are bad clients.

Option one the client could have a local blacklist, and when it gets a bad client from the scheduler just ask for another client. I have to check the code, but I think the scheduler will start preferring this bad client as it seems to work so fast...

Option two: the scheduler can have the clients ping each other and report what cannot be reached,thus building a per client blacklist.

Either way we need a way to expire the bad client list.  Otherwise when the problem is fixed the client still won't be used.  Worse, on a network where IPs change often you could end up blacklisting everything.

**Comment by HenryMiller1** [comment] 2016-04-07 16:23
I see this problem often. I've traced a few to running in a vm but not forwarding the icecc ports to the vm.  The clients can get out but nothing can get back in.

**Comment by coolo** [comment] 2016-04-07 20:09
the scheduler can check that situation at least - if it can't reach the daemon, it's bad

**Comment by michaeljs1990** [comment] 2016-05-10 15:39
I am seeing something similar...

```
ICECC[3717] 15:06:48: can't write to /tmp - compiled on 172.30.103.19
ICECC[3717] 15:06:48: got exception 23 (172.30.103.19)
```

I think it might be a litle different but the end result IMO would be the same. the scheduler or client stops trying to give out jobs to this node. I also had restart iceccd on every machine after shutting down the faulty node. Was this the right course of action or would icecc figure it out by itself if I waited longer?

Thanks,

**Comment by michaeljs1990** [comment] 2016-10-13 21:38
Client side checks seem to be the best way to handle this since like you said large networks can potentially have varying firewall rules. It seem the best way forward would be for the client to keep a list of all bad clients determined by return codes for X time before retrying. On small networks this could be undesirable since one or two failures could mean no icecc at all so a config option to disable this should satisfy all use cases.

**Comment by AlgorithMan-de** [comment] 2017-04-07 13:27
Well if a machine fails on 100% of the jobs it gets, then there is no good reason not to block it (at least for a while - say 5 minutes - may be configurable). Even if it's the only other machine in the network, blocking it deactivates icecc no less than continuing (trying) to use it... Actually - the smaller the network, the more significantly it slows down the compilation, when you don't block the machine...

**Comment by AlgorithMan-de** [comment] 2017-04-11 10:28
In our network we have 25 icecc clients and just 2 misbehaving clients bring a compilation process down so badly, you're better off compiling without icecc. It might have to do with the fact that the misbehaving clients have load 0 and might therefore be favored in the scheduling (?).

**Comment by HenryMiller1** [comment] 2017-04-11 15:23
@AlgorithMan-de that seems like a different issue, can report it separately?

**Comment by bschmer** [comment] 2017-04-17 14:37
@AlgorithMan-de I see the same type of behavior.  A compile that should be very fast is slowed significantly by hosts that are no longer responding.  This is extremely painful for those that experience the issue.  Doing a 15 minute look over the code, it appears that there appear to be mechanisms in place to blacklist hosts, so maybe what could be done is to trigger the blacklist check on a job failure or add a call that de-prioritizes the questionable host.

**Comment by mvslobbe** [comment] 2017-04-25 07:45
For what it's worth; I'm seeing similar errors:

ICECC[16209] 15:40:28: got exception 17 (192.168.168.78)

as well as 

ICECC[25972] 15:44:34: write of source chunk to host 192.168.168.159
ICECC[25972] 15:44:34: failed  Resource temporarily unavailable
ICECC[25972] 15:44:34: got exception 15 (192.168.168.159)

**Comment by HenryMiller1** [comment] 2017-04-25 15:08
@mvslobbe That looks like a different issue and should be reported separately.

I also see exception 17; write of source chunk to host failed fail; and exception 15 fairly often myself and I don't know how to debug them more.

**Comment by mvslobbe** [comment] 2017-04-26 09:02
Thanks @HenryMiller1. I've opened #228 for that.

Regardless of the specific exception ( be it 15, 17 or 23 as mentioned in this issue ) I believe that the overall topic of this issue wasn't so much about the various reasons why clients can be experiencing difficulties but rather to make the scheduler more fault-tolerant to misbehaving clients. I'd hope that that would give us a better outcome more easily.

**Comment by mbitsnbites** [comment] 2017-05-10 13:00
I agree with @mvslobbe. Misbehaving clients and/or misconfigured networks is a general problem that hurts ICECC performance badly, regardless of the reason (firewall, full disk, permission problems, bugs etc), so it would be nice to implement some catch-all workaround to make ICECC less sensitive to errors.

I'm on a ~15 nodes network (ICECC 1.0.1), and we get exception 23 several times per week (which seems to be due to missing toolchains - usually solved by restarting iceccd on the failing client).

These are indeed different issues, but question remains: Should #143 deal with the overall problem (I think so)?

**Comment by mbitsnbites** [comment] 2017-05-10 13:13
I added some information in #184 regarding exception 23.

**Comment by HenryMiller1** [comment] 2017-07-06 19:08
There was a lot of discussion on this issue. We have implemented on proposed fix, but there are lots of other ideas. I would like to close this issue at this point, I'm going to leave it open a few more days just to give all contributors a chance to look it over and extract any parts of this that they do not feel are address sufficiently into a new issue that is targeted to exactly the situation they feel could be better handled.

**Comment by HenryMiller1** [comment] 2017-08-08 18:24
Nobody has suggested anything more they want to do with this, closing.  Feel free to open new issues for any of the several sub-issues raised if they are your problem.

**Closed by HenryMiller1** 2017-08-08 18:24 UTC
