### ISSUE TITLE
Add an option to run the preprocessor again on the target machine

### ISSUE THREAD

**Issue by theres-waldo** [icecc/icecream#163] opened 2016-08-08 17:13 UTC
It would be nice if icecream had an option similar to ccache's [CCAHCE_CPP2](http://petereisentraut.blogspot.ca/2011/09/ccache-and-clang-part-2.html), to run the preprocessor again on the target machine, because some compilers give warnings on preprocessed code that they don't give on the original code, and this can be a problem when using -Werror.

**Comment by llunak** [comment] 2017-12-15 17:36
Duplicate of issue #240 .

**Closed by llunak** 2017-12-15 17:36 UTC
