### ISSUE TITLE
How do I limit the number of processes icecream uses locally?

### ISSUE THREAD

**Issue by zachyam** [icecc/icecream#485] opened 2019-07-12 17:36 UTC
I am running icecream locally on my machine using ninja. So, a typical command I would issue would be `ninja -j60`. 

My Mac freezes / lags whenever its running, and I was wondering if there is a way for me to prevent that from happening. Is there a config file where I can set the max number of processes?

Please let me know if more info is needed, and any advice would be appreciated.

**Comment by dionorgua** [comment] 2019-07-12 18:09
Firstly preprocessing also takes a lot of CPU resources. So consider reducing `-j` value to some lower value. Also you can take a look to `-l` option of ninja

**Comment by llunak** [comment] 2019-07-13 07:48
Duplicate of #285 .

**Closed by llunak** 2019-07-13 07:48 UTC
