### ISSUE TITLE
Compiling with -fprofile-generate

### ISSUE THREAD

**Issue by p2rkw** [icecc/icecream#156] opened 2016-05-12 10:45 UTC
What's the reason behind following checks https://github.com/icecc/icecream/blob/master/client/arg.cpp#L247 ?

Why does -fprofile-generate have to prevent distributed build?

**Comment by llunak** [comment] 2017-12-28 16:07
Because that makes the compiler generate additional output files that icecream doesn't send back, so it wouldn't work remotely anyway. See e.g. https://github.com/icecc/icecream/pull/303 .

**Comment by brs85** [comment] 2020-04-27 12:58
Hello,

New user here.
What is the status on Coverage with ICECC?
We are using ICECC to build with TeamCity and using Coverage. Is there another way of using ICECC with coverage?

**Comment by llunak** [comment] 2020-07-19 06:26
Duplicate of #187 , which has more information.

**Closed by llunak** 2020-07-19 06:26 UTC
