### ISSUE TITLE
debug fission tests fail in Ubuntu 14.04

### ISSUE THREAD

**Issue by HenryMiller1** [icecc/icecream#193] opened 2017-03-17 20:50 UTC
When running tests on ubuntu trust 14.04 they fail as follows.  I have gone back in history and determined that these tests have never passed on trusty since they were introduced.

```
icecc --build-native test successful.

Starting icecream.
Starting icecream successful.

Running: /usr/bin/g++ -Wall -Werror -gsplit-dwarf -g -c plain.cpp -o /home/hm68841/workspace/icecream-upstream/ice-test/tests/results/plain.o
Files /home/hm68841/workspace/icecream-upstream/ice-test/tests/results/plain.o.remote.readelf.txt and /home/hm68841/workspace/icecream-upstream/ice-test/tests/results/plain.o.readelf.txt differ
Output mismatch (/home/hm68841/workspace/icecream-upstream/ice-test/tests/results/plain.o.remoteice)
make[2]: *** [test-run] Error 2
make[2]: Leaving directory `/home/hm68841/workspace/icecream-upstream/ice-test/tests'
make[1]: *** [test-full] Error 2
make[1]: Leaving directory `/home/hm68841/workspace/icecream-upstream/ice-test/tests'
make: *** [test] Error 2
```

The differences look small, but I have not looked into them

```
diff /home/hm68841/workspace/icecream-upstream/ice-test/tests/results/plain.o.remote.readelf.txt /home/hm68841/workspace/icecream-upstream/ice-test/tests/results/plain.o.readelf.txt
4c4
<    Length:        0x73 (32-bit)
---
>    Length:        0xac (32-bit)
15,16c15,16
<     <73>   DW_AT_GNU_pubnames: 1	
<     <73>   DW_AT_GNU_addr_base: 0x0	
---
>     <ac>   DW_AT_GNU_pubnames: 1	
>     <ac>   DW_AT_GNU_addr_base: 0x0	
37c37
<   Size of area in .debug_info section: 288
---
>   Size of area in .debug_info section: 189
40c40
<     109   	f
---
>     a6    	f
47c47
<   Size of area in .debug_info section: 288
---
>   Size of area in .debug_info section: 189
```

**Comment by HenryMiller1** [comment] 2017-03-17 20:51
You can see that this is not unique to me, https://travis-ci.org/HenryMiller1/icecream/builds/212227718 sees the same thing

**Comment by johnmiked15** [comment] 2017-03-17 22:28
This test has passed for me since I first committed it. If this isn't passing, I'd like to know what's going on.

What compiler version is trusty using? What version of binutils?

Is /usr/bin/g++ a symlink to something else? Maybe the environment tarball that is getting created is pulling different files than the local system is using. Can you compare the contents of the environment tarball and the system?

**Comment by HenryMiller1** [comment] 2017-03-20 21:09
$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

usr/bin/gcc is a symlink to gcc-4.8.  it looks to me like the environment is correct, though I'm still investigating.

**Comment by HenryMiller1** [comment] 2017-03-21 15:00
This test is still failing on ubuntu trusty. 

Note that gcc -E -gsplit-dwarf tests/messages.cpp
returns 0

**Comment by johnmiked15** [comment] 2017-03-21 15:42
Yes, gcc 4.8 supports `-gsplit-dwarf`. There is something else going on here. It might be a bug in the version of binutils that is installed on 14.04. What is the version of binutils?

Please paste the diff again, but use `-u`: `diff -u plain.o.remote.readelf.txt plain.o.readelf.txt`

**Comment by HenryMiller1** [comment] 2017-03-21 17:57
```
@@ -1,7 +1,7 @@
 Contents of the .debug_info section:
 
   Compilation Unit @ offset 0x0:
-   Length:        0x73 (32-bit)
+   Length:        0xac (32-bit)
    Version:       4
    Abbrev Offset: 0x0
    Pointer Size:  8
@@ -12,8 +12,8 @@
     <20>   
     <28>   
     <61>   
-    <73>   DW_AT_GNU_pubnames: 1	
-    <73>   DW_AT_GNU_addr_base: 0x0	
+    <ac>   DW_AT_GNU_pubnames: 1	
+    <ac>   DW_AT_GNU_addr_base: 0x0	
 
 Contents of the .debug_abbrev section:
 
@@ -34,17 +34,17 @@
   Length:                              20
   Version:                             2
   Offset into .debug_info section:     0x0
-  Size of area in .debug_info section: 288
+  Size of area in .debug_info section: 189
 
     Offset	Name
-    109   	f
+    a6    	f
 
 Contents of the .debug_pubtypes section:
 
   Length:                              14
   Version:                             2
   Offset into .debug_info section:     0x0
-  Size of area in .debug_info section: 288
+  Size of area in .debug_info section: 189
 
     Offset	Name
```

**Comment by johnmiked15** [comment] 2017-03-21 19:10
binutils?

**Comment by HenryMiller1** [comment] 2017-03-21 19:19
binutils	2.24-5ubuntu14.1

ar --version
GNU ar (GNU Binutils for Ubuntu) 2.24

**Comment by derekgorcz** [comment] 2017-04-12 15:14
The test uses a sed command to remove the DW_AT_GNU_dwo_name as well as some other things before doing a diff against the elf files.

Here is the output for the working version of gcc:
```
                   Length:        0x30 (32-bit)
                   Version:       4
                   Abbrev Offset: 0x0
                   Pointer Size:  8
                <0><b>: Abbrev Number: 1 (DW_TAG_compile_unit)
                    <c>   DW_AT_low_pc      : 0x0
                    <14>   DW_AT_high_pc     : 0x7
                    <1c>   DW_AT_stmt_list   : 0x0
                    <20>   DW_AT_GNU_dwo_name: (indirect string, offset: 0x0): /home/derek/icecream-build/tests/results/plain.dwo
                    <24>   DW_AT_comp_dir    : (indirect string, offset: 0x33): /home/derek/icecream-build/tests
                    <28>   DW_AT_GNU_pubnames: 1
                    <28>   DW_AT_GNU_addr_base: 0x0
                    <2c>   DW_AT_GNU_dwo_id  : 0xcd67f39a0424c27d
```
For the remote chrooted environment the dwo_name is different and possibly the comp_dir as well (which is the reason for the sed command).
The output without sed is:
```
                    <20>   DW_AT_GNU_dwo_name: (indirect string, offset: 0x0): results/plain.dwo
                    <24>   DW_AT_comp_dir    : (indirect string, offset: 0x12): /home/derek/icecream-build/tests
```
For the g++ versions available in trusty, those strings are stored slightly differently. 
Here is an example:
```
  Compilation Unit @ offset 0x0:
   Length:        0x66 (32-bit)
   Version:       4
   Abbrev Offset: 0x0
   Pointer Size:  8
<0><b>: Abbrev Number: 1 (DW_TAG_compile_unit)
    <c>   DW_AT_low_pc      : 0x0       
    <14>   DW_AT_high_pc     : 0x6      
    <1c>   DW_AT_stmt_list   : 0x0      
    <20>   DW_AT_GNU_dwo_id  : 0xf2e2bf3ea8d809b3       
    <28>   DW_AT_comp_dir    : /home/dg74123/Documents/icecream-build   
    <4f>   DW_AT_GNU_dwo_name: manual_tests/plain.dwo   
    <66>   DW_AT_GNU_pubnames: 1        
    <66>   DW_AT_GNU_addr_base: 0x0   
```
With this version you will notice that <4f> is offset by 27 from <28> which is the length of “/home/dg74123/Documents/icecream-build\0 ” where as in the newer gcc the offset is always 4 because it’s using a reference of some sort.
To me this seems like an issue with the test unless icecream is dependent on a specific type of behavior here in some way?

**Comment by johnmiked15** [comment] 2017-04-12 16:06
It is somewhat important that the paths are correct, but the way gdb loads these files is somewhat arbitrary.

Since you have already done an awesome job of setting up a reproducible environment for both a working and non working version, could you go one step further and actually attempt to load an executable in gdb and see if it finds the debug symbol information correctly? If it does, then the test is wrong for the failing case. If it doesn't, then something else is going on with that gcc version.

**Comment by derekgorcz** [comment] 2017-04-12 16:26
Yes, I have tested gdb and it seems like it works just fine.
For `gdb plain.o.localice`
```
(gdb) list
1	void f()
2	    {
3	    }
```
And `gdb plain.o.remoteice`
```
(gdb) list
1	void f()
2	    {
3	    }
```

**Comment by johnmiked15** [comment] 2017-04-12 16:30
That's just printing the source file. Try going a few stack frames deep and print a back trace. That should show the proper function names. Might need a new cpp file.

**Comment by derekgorcz** [comment] 2017-04-12 18:27
I created a test.o library with -gsplit-dwarf and used it in an executable. Seems ok and unaffected by a different working directory.
```
Reading symbols from /tmp/tmp.wKUYZoLNaV/test...done.
(gdb) list
1	#include "test.h"
2	
3	int main()
4	{
5	    return f1() + f2();
6	}
(gdb) br f3
Breakpoint 1 at 0x400528: file test.cpp, line 16.
(gdb) run
Starting program: /tmp/tmp.wKUYZoLNaV/test 

Breakpoint 1, f3 () at test.cpp:16
16	    return 2;
(gdb) list
11	}
12	
13	
14	int f3()
15	{
16	    return 2;
17	}
(gdb) bt
#0  f3 () at test.cpp:16
#1  0x000000000040051f in f2 () at test.cpp:10
#2  0x0000000000400502 in main () at main.cpp:5
```
Since split-dwarf was used when compiling the library but not the executable, you can see that the compilation unit of the executable uses the "indirect string" for the DW_AT_name and DW_AT_comp_dir, while the library compilation unit(nested) does not.
```
  Compilation Unit @ offset 0x0:
   Length:        0x4e (32-bit)
   Version:       4
   Abbrev Offset: 0x0
   Pointer Size:  8
 <0><b>: Abbrev Number: 1 (DW_TAG_compile_unit)
    <c>   DW_AT_producer    : (indirect string, offset: 0x1d): GNU C++ 4.8.4 -mtune=generic -march=x86-64 -g -fstack-protector  
    <10>   DW_AT_language    : 4    (C++)
    <11>   DW_AT_name        : (indirect string, offset: 0x14): main.cpp    
    <15>   DW_AT_comp_dir    : (indirect string, offset: 0x0): /tmp/tmp.wKUYZoLNaV  
    <19>   DW_AT_low_pc      : 0x4004ed 
    <21>   DW_AT_high_pc     : 0x1e 
    <29>   DW_AT_stmt_list   : 0x0  
 <1><2d>: Abbrev Number: 2 (DW_TAG_subprogram)
    <2e>   DW_AT_external    : 1    
    <2e>   DW_AT_name        : (indirect string, offset: 0x5d): main    
    <32>   DW_AT_decl_file   : 1    
    <33>   DW_AT_decl_line   : 3    
    <34>   DW_AT_type        : <0x4a>   
    <38>   DW_AT_low_pc      : 0x4004ed 
    <40>   DW_AT_high_pc     : 0x1e 
    <48>   DW_AT_frame_base  : 1 byte block: 9c     (DW_OP_call_frame_cfa)
    <4a>   DW_AT_GNU_all_tail_call_sites: 1 
 <1><4a>: Abbrev Number: 3 (DW_TAG_base_type)
    <4b>   DW_AT_byte_size   : 4    
    <4c>   DW_AT_encoding    : 5    (signed)
    <4d>   DW_AT_name        : int  
 <1><51>: Abbrev Number: 0
  Compilation Unit @ offset 0x52:
   Length:        0x45 (32-bit)
   Version:       4
   Abbrev Offset: 0x37
   Pointer Size:  8
 <0><5d>: Abbrev Number: 1 (DW_TAG_compile_unit)
    <5e>   DW_AT_low_pc      : 0x40050b 
    <66>   DW_AT_high_pc     : 0x24 
    <6e>   DW_AT_stmt_list   : 0x3c 
    <72>   DW_AT_GNU_dwo_id  : 0x7eda922a76757878   
    <7a>   DW_AT_comp_dir    : /tmp/tmp.wKUYZoLNaV  
    <8e>   DW_AT_GNU_dwo_name: test.dwo 
    <97>   DW_AT_GNU_pubnames: 1    
    <97>   DW_AT_GNU_addr_base: 0x0 
```

**Closed** 2017-04-19 21:59 UTC
