### ISSUE TITLE
Remote clang++ compilation fails with "unknown type name '__u64'"

### ISSUE THREAD

**Issue by eeejay** [icecc/icecream#503] opened 2019-09-17 22:56 UTC
## Steps to reproduce

Given this program:
```cpp
#include <sys/stat.h>
#include <sys/quota.h>

int foo() {
  return 1;
}
```
If I try to compile it with `clang++`, like this:
```
ICECC_DEBUG=debug ICECC_PREFERRED_HOST=<remote-ip> /usr/libexec/icecc/bin/clang t.cpp -c -o t.o
```

I get the following error:
<pre>ICECC[4889] 2019-09-17 15:53:08: invoked as: /usr/libexec/icecc/bin/clang t.cpp -c -o t.o
ICECC[4889] 2019-09-17 15:53:08: connected to /var/run/icecc/iceccd.socket
ICECC[4889] 2019-09-17 15:53:08: native /var/cache/icecream/native/2a33006b72527196077fd9333f409264.tar.gz
ICECC[4889] 2019-09-17 15:53:08: env: x86_64 &apos;/var/cache/icecream/native/2a33006b72527196077fd9333f409264.tar.gz&apos;
ICECC[4889] 2019-09-17 15:53:08: preparing t.cpp to be compiled for x86_64
ICECC[4889] 2019-09-17 15:53:08: Have to use host 10.25.13.124:10245 - Job ID: 11570 - env: x86_64 - has env: true - match j: 0
ICECC[4889] 2019-09-17 15:53:08: connected to 10.25.13.124
ICECC[4889] 2019-09-17 15:53:08: &lt;send compile_file&gt;
ICECC[4889] 2019-09-17 15:53:08: &lt;/send compile_file: 0ms&gt;
ICECC[4889] 2019-09-17 15:53:08: &lt;write_server_cpp from cpp&gt;
ICECC[4892] 2019-09-17 15:53:08: preparing source to send: /usr/bin/clang -fcolor-diagnostics -E t.cpp -frewrite-includes
ICECC[4889] 2019-09-17 15:53:08: sent 64648 bytes (34%)
ICECC[4889] 2019-09-17 15:53:08: &lt;/write_server_cpp from cpp: 52ms&gt;
ICECC[4889] 2019-09-17 15:53:08: &lt;wait for cpp&gt;
ICECC[4889] 2019-09-17 15:53:08: &lt;/wait for cpp: 0ms&gt;
ICECC[4889] 2019-09-17 15:53:08: &lt;wait for cs&gt;
ICECC[4889] 2019-09-17 15:53:08: &lt;/wait for cs: 50ms&gt;
In file included from t.cpp:2:
In file included from /usr/include/sys/quota.h:57:
<b>/usr/include/linux/quota.h:111:2: </b><font color="#CC0000"><b>error: </b></font><b>unknown type name &apos;__u64&apos;</b>
        __u64 dqb_bhardlimit;
<font color="#4E9A06"><b>        ^</b></font>
<b>/usr/include/linux/quota.h:112:2: </b><font color="#CC0000"><b>error: </b></font><b>unknown type name &apos;__u64&apos;</b>
        __u64 dqb_bsoftlimit;
<font color="#4E9A06"><b>        ^</b></font>
<b>/usr/include/linux/quota.h:113:2: </b><font color="#CC0000"><b>error: </b></font><b>unknown type name &apos;__u64&apos;</b>
        __u64 dqb_curspace;
<font color="#4E9A06"><b>        ^</b></font>
<b>/usr/include/linux/quota.h:114:2: </b><font color="#CC0000"><b>error: </b></font><b>unknown type name &apos;__u64&apos;</b>
        __u64 dqb_ihardlimit;
<font color="#4E9A06"><b>        ^</b></font>
<b>/usr/include/linux/quota.h:115:2: </b><font color="#CC0000"><b>error: </b></font><b>unknown type name &apos;__u64&apos;</b>
        __u64 dqb_isoftlimit;
<font color="#4E9A06"><b>        ^</b></font>
<b>/usr/include/linux/quota.h:116:2: </b><font color="#CC0000"><b>error: </b></font><b>unknown type name &apos;__u64&apos;</b>
        __u64 dqb_curinodes;
<font color="#4E9A06"><b>        ^</b></font>
<b>/usr/include/linux/quota.h:117:2: </b><font color="#CC0000"><b>error: </b></font><b>unknown type name &apos;__u64&apos;</b>
        __u64 dqb_btime;
<font color="#4E9A06"><b>        ^</b></font>
<b>/usr/include/linux/quota.h:118:2: </b><font color="#CC0000"><b>error: </b></font><b>unknown type name &apos;__u64&apos;</b>
        __u64 dqb_itime;
<font color="#4E9A06"><b>        ^</b></font>
<b>/usr/include/linux/quota.h:119:2: </b><font color="#CC0000"><b>error: </b></font><b>unknown type name &apos;__u32&apos;</b>
        __u32 dqb_valid;
<font color="#4E9A06"><b>        ^</b></font>
<b>/usr/include/linux/quota.h:123:2: </b><font color="#CC0000"><b>error: </b></font><b>unknown type name &apos;__u64&apos;</b>
        __u64 dqb_bhardlimit;
<font color="#4E9A06"><b>        ^</b></font>
<b>/usr/include/linux/quota.h:124:2: </b><font color="#CC0000"><b>error: </b></font><b>unknown type name &apos;__u64&apos;</b>
        __u64 dqb_bsoftlimit;
<font color="#4E9A06"><b>        ^</b></font>
<b>/usr/include/linux/quota.h:125:2: </b><font color="#CC0000"><b>error: </b></font><b>unknown type name &apos;__u64&apos;</b>
        __u64 dqb_curspace;
<font color="#4E9A06"><b>        ^</b></font>
<b>/usr/include/linux/quota.h:126:2: </b><font color="#CC0000"><b>error: </b></font><b>unknown type name &apos;__u64&apos;</b>
        __u64 dqb_ihardlimit;
<font color="#4E9A06"><b>        ^</b></font>
<b>/usr/include/linux/quota.h:127:2: </b><font color="#CC0000"><b>error: </b></font><b>unknown type name &apos;__u64&apos;</b>
        __u64 dqb_isoftlimit;
<font color="#4E9A06"><b>        ^</b></font>
<b>/usr/include/linux/quota.h:128:2: </b><font color="#CC0000"><b>error: </b></font><b>unknown type name &apos;__u64&apos;</b>
        __u64 dqb_curinodes;
<font color="#4E9A06"><b>        ^</b></font>
<b>/usr/include/linux/quota.h:129:2: </b><font color="#CC0000"><b>error: </b></font><b>unknown type name &apos;__u64&apos;</b>
        __u64 dqb_btime;
<font color="#4E9A06"><b>        ^</b></font>
<b>/usr/include/linux/quota.h:130:2: </b><font color="#CC0000"><b>error: </b></font><b>unknown type name &apos;__u64&apos;</b>
        __u64 dqb_itime;
<font color="#4E9A06"><b>        ^</b></font>
<b>/usr/include/linux/quota.h:131:2: </b><font color="#CC0000"><b>error: </b></font><b>unknown type name &apos;__u32&apos;</b>
        __u32 dqb_valid;
<font color="#4E9A06"><b>        ^</b></font>
<b>/usr/include/linux/quota.h:132:2: </b><font color="#CC0000"><b>error: </b></font><b>unknown type name &apos;__u32&apos;</b>
        __u32 dqb_id;
<font color="#4E9A06"><b>        ^</b></font>
<font color="#CC0000"><b>fatal error: </b></font>too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
ICECC[4889] 2019-09-17 15:53:08: Compiled on 10.25.13.124
</pre>

## More notes

* Both local and remote machines are Fedora 30.
* This works if I compile this as a C program with `clang`.
* This works with local compilation.
* If I swap the order of the two include lines in the file, it works.

**Comment by llunak** [comment] 2019-09-18 19:28
> If I try to compile it with `clang++`, like this:
> 
> ```
> ICECC_DEBUG=debug ICECC_PREFERRED_HOST=<remote-ip> /usr/libexec/icecc/bin/clang t.cpp -c -o t.o
> ```

There is no 'clang++' anywhere in that command or in the logs. Does actually using it make a difference?

Also, if it doesn't, please try the command with both ICECC_REMOTE_CPP=1 and ICECC_REMOTE_CPP=0. If either of those helps, then also try
```
clang++ -E -frewrite-includes t.cpp >t2.cpp
clang++ -c t2.cpp -o t.o

```
and if this fails, then please attach t2.cpp .

**Comment by eeejay** [comment] 2019-09-18 19:29
I managed to reproduce this in tests as well, if you change `tests/plain.cpp` to, and use clang.
```cpp
#include <sys/stat.h>
#include <sys/quota.h>

void f()
    {
    }
```

This seems to be an issue with glibc 2.30 (and uplifted to 2.29 in fedora 30??), with the introduction of `statx.h`, and the conditional macro [there](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/bits/statx.h;h=ff3f2e897357b7eabdfeef04750622d1bcb72981).

**Comment by eeejay** [comment] 2019-09-18 19:49
Here are the interesting bits, given the `plain.cpp` above,

* This is the [preprocessed source](https://github.com/icecc/icecream/files/3628070/preprocessed_plain_cpp.txt) that gets sent to the server with `-frewrite-includes`.
* On my local machine, if I do `clang -E` on it, it will get 
[fully preprocessed](https://github.com/icecc/icecream/files/3628078/expanded_not_in_chroot_cpp.txt), I can the compile that file with no problem.
* If I do `clang -E` in the server's chroot environment, I get [this preprocessed file](https://github.com/icecc/icecream/files/3628086/expanded_in_chroot_cpp.txt). This is indeed a broken source since it is missing the types above, like `__u64`.

It looks like the issue is in line 2643 of the first `rewrite-includes` file, where we have a conditional:
```cpp
#if __glibc_has_include ("linux/stat.h")
```
I guess as a workaround I can disable remote preprocessing, but I hope all this helps!

**Comment by llunak** [comment] 2019-09-18 20:34
I see. This is a duplicate of #471 . I've already fixed that in Clang, unfortunately it missed Clang-9 and will be available with Clang-10. One workaround is to use ICECC_REMOTE_CPP=0, another one is adding "-include linux/stat.h" to your CXXFLAGS (I suggest the latter).

**Closed by llunak** 2019-09-18 20:34 UTC
Labels: needinfo
