### ISSUE TITLE
icecc and bitbake

### ISSUE THREAD

**Issue by vbce** [icecc/icecream#419] opened 2018-09-21 21:14 UTC
Hi!
I've tried using ICECC with Yocto bitbake for my aarch64 project. It seems to work fine, though I've observed the following issue with a number of packets. Everything works fine with no ICECC support.
With ICECC enabled some packets -- for example: elfutils, json-c -- fail to compile with the following error:
`error: this statement may fall through [-Werror=implicit-fallthrough=]`
This happens only with cross-compilation and can be reproduced when cross-compiling elfutils-0.170 without bitbake.
What could possibly cause this behaviour and how to workaround the issue?

I'm using the latest icecream 1.1.90.
BTW, I'd seen other build issues but I managed to workaround them by rebuilding icecc with the following option: --disable-gcc-fdirectives-only. Looks like remote preprocessing doesn't always work.
Thanks in advance!

**Comment by bauerjj** [comment] 2018-09-26 20:34
Are you enabling parallel builds (make -j8) for `elfutils` when you build without icecc outside of bitbake? I've noticed that some libs simply cannot be built with more than one task without some odd errors. Have you also tried a different version of gcc?

**Comment by vbce** [comment] 2018-09-27 10:10
> Are you enabling parallel builds (make -j8) for `elfutils` when you build without icecc outside of bitbake? 

I've tried compiling with icecc and with no icecc, using -j8 -j16 and -j1, with the same results: non-icecc compilation doesn't fail, while icecc fails at implicit-fallthrough.

>Have you also tried a different version of gcc?

I've noticed this with gcc 7.3.0. Other gcc versions I use are quite old and do not support -Werror=implicit-fallthrough option. I've tried looking a bit deeper into it. It looks like the comments are dropped during preprocessing in icecc. Thus, the /* Fallthrough */ comments are removed from the switch statements. When the preprocessed file is then compiled with -Werror=implicit-fallthrough option, it fails. I'm not sure how exactly icecc does the preprocessing step, but looks like -C option has to be enabled along with -E. Though I'm not sure whether keeping the comments in preprocessed files might cause other issued.

Thanks!

**Comment by llunak** [comment] 2019-06-02 12:41
The problem is that --disable-gcc-fdirectives-only makes the local run process the source using a preprocessor, which also removes comments. So presumably what happens is that the relevant source has switch with /* fallthough */, which normally prevents the warning, but here it gets removed.

You basically have these options:
- get -fdirectives-only working (which may involve fixing the problems in gcc)
- disable the warning, or at least do not turn it into an error
- use Clang instead of GCC

As long as -fdirectives-only doesn't work, I don't think Icecream can do anything about this problem.

**Comment by llunak** [comment] 2019-07-18 17:03
As said above, there's really not that much to do about this in Icecream, closing.

**Closed by llunak** 2019-07-18 17:03 UTC
