### ISSUE TITLE
Icecream is not passing compiler flags from ninja's response files to the compiler

### ISSUE THREAD

**Issue by tpopela** [icecc/icecream#188] opened 2017-02-23 11:12 UTC
If using cmake 3.6+ together with ninja and have the support for the ninja's response files enabled (`CMAKE_NINJA_FORCE_RESPONSE_FILE`) to avoid problems with exceeding maximum command line length, then the icecream is not passing the flags from these files to the compiler and build could fail (in our case it was not passing `-fPIC`).

For more details please see https://gitlab.kitware.com/cmake/cmake/issues/16664 .

**Comment by RedBeard0531** [comment] 2017-03-28 14:15
I think the problem is here: https://github.com/icecc/icecream/blob/master/client/arg.cpp#L474-L475. That block should either set `always_local = true` or recursively process all flags in the response file.

**Comment by dantje** [comment] 2017-12-26 11:16
I would argue a better solution would be to call expandargv() from libiberty, which is what other tools that support response files do. This call happens right at the top of main() and replace all response files in argv with their contents.

distcc also added this a while ago.

One possible downside is the added dependency -- e.g. libiberty on ubuntu now seems to be bundled in binutils-dev and the header file seems to have been moved over time. On the other hand, if distcc is packaged on the same platform, this is a solved problem. Plus one can always disable the support via configure.

Or would it be ok to just include a verbatim copy of expandargv()/libiberty in the repo?  icecc is GPL 2.0 and libiberty is LGPL 2.1. This would do away with any packaging problem.

distcc used to include libiberty once at added a happy note in the NEWS file when they got rid of that...

**Comment by llunak** [comment] 2017-12-26 17:04
License-wise it should be ok to include the code itself directly, and libiberty's docs even seem to suggest that. Copying only the relevant file/function to icecream/client/ should do.

**Comment by HenryMiller1** [comment] 2017-12-26 18:45
Debian at least will not allow that. If we include the code it needs to
build with the system library if possible.
--
  Henry Miller
  hank@millerfarm.com



On Tue, Dec 26, 2017, at 11:04 AM, Luboš Luňák wrote:
> License-wise it should be ok to include the code itself directly, and
> libiberty's docs even seem to suggest that. Copying only the relevant
> file/function to icecream/client/ should do.> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 

Links:

  1. https://github.com/icecc/icecream/issues/188#issuecomment-353990211

**Comment by llunak** [comment] 2017-12-26 19:01
Icecream shipped a copy of (mini)lzo for ages and they didn't have a problem with that. I seriously doubt they'd even notice a copy&paste of one function. But if they do complain about it even if the library itself suggests it, they're free to patch it to whatever they want without complicating life for everyone else.

**Comment by mathstuf** [comment] 2018-01-02 18:26
@HenryMiller1 FWIW, Fedora fought this battle for a long time (gnulib and libiberty are designed to be embedded into other projects) and ended up just making sure that embedded copies are at least declared (`Provides: bundled(gnulib) = 1.0.0` or the like).

**Comment by dantje** [comment] 2018-01-07 10:46
#327 now implements the expandargv() part on the client side. The daemon already invokes execv(), so it should not be subject to any shell limits wrt the number of arguments or length of the command line.

This would fail if the invoked compiler driver is a shell wrapper that tries to relay all arguments to the actual compiler.

On a related note, I saw a commit in clang that adds something that looks suspiciously like responsefiles (https://reviews.llvm.org/rL321587).

**Comment by llunak** [comment] 2018-01-07 12:27
#327 has been merged, so closing.

Note that the invoked compiler driver cannot be a script (icecc-create-env wouldn't handle that).

**Closed by llunak** 2018-01-07 12:27 UTC
