### ISSUE TITLE
clang-4.0 tries to read /proc/cpuinfo and failed

### ISSUE THREAD

**Issue by kanru** [icecc/icecream#176] opened 2016-11-24 03:31 UTC
```
 0:05.57 checking for the target C compiler... /usr/bin/clang
 0:05.69 checking whether the target C compiler can be used... yes
 0:05.69 checking the target C compiler version... 4.0.0
 0:14.61 checking the target C compiler works... no
 0:14.61 DEBUG: Creating `/tmp/conftest.mtiJyc.c` with content:
 0:14.61 DEBUG: |
 0:14.61 DEBUG: | int
 0:14.61 DEBUG: | main(void)
 0:14.61 DEBUG: | {
 0:14.61 DEBUG: |
 0:14.61 DEBUG: |   ;
 0:14.61 DEBUG: |   return 0;
 0:14.61 DEBUG: | }
 0:14.61 DEBUG: Executing: `/usr/bin/icecc /usr/bin/clang -std=gnu99 -c /tmp/conftest.mtiJyc.c`
 0:14.61 DEBUG: The command returned non-zero exit status 105.
 0:14.61 DEBUG: Its error output was:
 0:14.61 DEBUG: | Can't read /proc/cpuinfo: No such file or directory
 0:14.61 DEBUG: | ICECC[6490] 10:54:26: Compiled on 10.247.28.122
 0:14.61 ERROR: Failed compiling a simple C source with the target C compiler
```

**Comment by coolo** [comment] 2016-11-24 11:18
so how to disable this?

**Comment by kanru** [comment] 2016-11-24 11:48
I don't know. It looks like it can't be disabled from command line arguments. Maybe I should file a clang bug too.

**Comment by coolo** [comment] 2016-11-24 12:17
For now I see only one way to fix this: disable remote compilation for clang. There is little value on optimizing for the CPU of the remote host anyway.

**Comment by kanru** [comment] 2016-11-24 13:47
Ah, please don't disable remote compilation for clang. Since clang 4.0 has not been released yet, I think they will accept a patch that adds flags to control this. Then we can disable it in iceccd.

**Comment by kito-cheng** [comment] 2017-01-03 03:32
Try --addfile /proc/cpuinfo when use icecc-create-env?

**Comment by pprkut** [comment] 2017-04-15 14:25
llvm 4.0 was released in the meantime, and the problem is still present.
Creating the environment using "icecc --build-native clang /proc/cpuinfo" however seems to work at least.

AFAICS the change was introduced with https://reviews.llvm.org/D25564 and doesn't even effect compiling, only linking.

**Comment by HenryMiller1** [comment] 2017-04-17 14:01
This seems like something I want fixed for Release 1.1, but I don't know how to do anything about it. Can someone work on this?

**Comment by RedBeard0531** [comment] 2017-04-25 13:14
clang seems happy with an empty /proc/cpuinfo so just touching the file in icecc-create-env does the trick:
https://github.com/RedBeard0531/mongo_module_ninja/commit/4fb8bc2864664553c51e555416072b81822f81f6. Since an empty file shouldn't have an appreciable effect on env size, I figured it just made sense to always add the file rather than detecting if it is needed.

PS: I've made a few other changes to that file to make it work better on more platforms (I've got gcc and clang working on fedora, ubuntu, and arch, along with a custom toolchain under /opt). When I find some time, I'll try to make proper pull requests, but if I don't get to it before you want to do a 1.1 release, feel free to just take whatever you want from https://github.com/RedBeard0531/mongo_module_ninja/commit/3d582c85393deef710f4b53367ed3d70684369db#diff-0ba0510e38e2771c877b39ab7d6d7e90.

**Comment by HenryMiller1** [comment] 2017-04-25 15:43
seems like we can pull clang-4.0 in our travis-ci framework and ensure that this works even after other other changes are made...

**Comment by HenryMiller1** [comment] 2017-04-25 17:08
It does seem like we should put proc/cpuinfo in the environment if it exists.   At least when not cross compiling we probably want to give clang hints on what CPU to optimize for.  When cross compiling we might want to allow the user to specify an alternative cpuinfo?

**Comment by RedBeard0531** [comment] 2017-04-25 17:25
As an alternative, how hard would it be to bind-mount /proc into the chroot in the daemon? While it would require a daemon upgrade to work with clang-4.0, it would present the correct info to clang about the machine it is running on, which is what /proc/cpuinfo seems to be used for. It may also address the issues I ran into with https://github.com/tpoechtrager/osxcross.

**Comment by K1773R** [comment] 2017-04-25 17:29
runs as root in chroot, you think giving access to /proc is wise?

**Comment by RedBeard0531** [comment] 2017-04-25 17:32
I assumed that root was only used to set up the chroot, then privileges were dropped before running the shipped compiler. If that is the case, then this isn't providing any new permissions. If that isn't the case, then there are bigger problems...

**Comment by pprkut** [comment] 2017-04-25 17:42
So, pasting from the review request I linked before:

```
This is to be used for setting the default parallelism for ThinLTO
backends (instead of thread::hardware_concurrency which includes
hyperthreading and is too aggressive). I'll send this as a follow-on
patch, and it will fall back to hardware_concurrency when the new
getHostNumPhysicalCores returns -1 (when not supported for a given
host system).
```
I assume whatever ThinLTO constitutes will run on the origin node, not anywhere remotely and in that case the contents of /proc/cpuinfo wouldn't matter.
The fallback behavior would match the report that it also works with an empty /proc/cpuinfo

**Comment by HenryMiller1** [comment] 2017-04-25 18:51
I think the empty file in icecc-create-env is the correct answer, it is enough to get this to work and hat is all we need. Note that the commit comment in clang says this is for LTO - icecream always does linking on the local machine where presumably /proc/cpuinfo is already available and correct. Clang might even accept a bug report that they are reading /proc/cpuinfo when they won't use that information???  (feel free to follow up with clang on this - my analysis might be wrong and they are more likely to know where)

Other reasons not to mount /proc:

While we document that you should only run icecream on a trusted network, in practice icecream is used at conferences where that isn't fully the case. Also there is a difference between assuming secure, and doing things that could lower security for no reason.

There is the future risk that clang might start using proc/cpuinfo for more than just parallelism - if they start detecting the CPU that way to do CPU specific optimizations. I already have problems because some of the x86 systems I run on do not have moveb while others do (I'm specifically optimizing for a CPU/target that supports moveb, but sometimes I want to test the code locally - this is a somewhat different situation)

Last, since icecream is used for large parallel builds in a number of cases the overall performance of the build might be best when clang runs with a single thread.  One thread means there is less lock overhead in clang, and is probably more cache friendly overall. The build system should be kicking off more compile jobs (which needs to be preprocessed locally) to keep all the CPUs busy, so there isn't any gain from adding threads to make all the local CPUs busy as well.  This of course doesn't apply to the last link in a build, but in a large build it applies to most of the rest.

Does the above make sense?  I'm still wrapping my mind around this issue.

**Comment by HenryMiller1** [comment] 2017-04-25 19:10
iceccd will drop permissions in the chroot if possible, but there are a few failure cases (often user error) where it cannot. In any case chroot has never been meant as a security feature, it provides some but not enough.

**Comment by coolo** [comment] 2017-04-26 08:13
if this is just about /proc/cpuinfo you can just as well copy the file from host to chroot before calling gcc.

**Comment by mostynb** [comment] 2017-04-30 21:17
I am unable to reproduce this error with clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz

This succeeds for me (and the icecc debug log tells me that the build is running remotely, tested with multiple remote machines):
icecc-create-env --clang /tmp/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-16.04/bin/clang
export ICECC_VERSION=1cdcacc90a34b3e6ad6bef5e64630bdb.tar.gz
icecc /tmp/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-16.04/bin/clang -std=gnu99 -c hello_world.c

**Comment by clopez** [comment] 2017-05-05 14:47
This works for me:

```
/usr/lib/icecc/icecc-create-env --clang /usr/bin/clang /usr/lib/icecc/compilerwrapper --addfile /usr/bin/objcopy --addfile /proc/cpuinfo
```

**Comment by HenryMiller1** [comment] 2017-05-05 18:00
@clopez objcopy should not be needed anymore, icecc-create-env adds it automaticaly if it exists.

**Comment by HenryMiller1** [comment] 2017-05-11 20:25
I asked the clang mailing list and their consensus is this is a bug in clang.  You can see the discussion on http://lists.llvm.org/pipermail/cfe-dev/2017-May/053782.html You can follow their progress on the bug at https://bugs.llvm.org/show_bug.cgi?id=33008

I think the right thing for us to do is document this bug in the work around for those who need it and hope clang fixes it soon.  It is possible we will need /proc/cpuinfo in the chroot for something else in the future, but it doesn't seem to be needed today.

**Closed** 2017-05-11 20:25 UTC
Labels: in progress
