### ISSUE TITLE
icecc hosts fail with a 'Resource temporarily unavailable' error

### ISSUE THREAD

**Issue by mvslobbe** [icecc/icecream#228] opened 2017-04-26 08:56 UTC
This comes up often on our small network of about twenty hosts:

ICECC[25972] 15:44:34: write of source chunk to host 192.168.0.15
ICECC[25972] 15:44:34: failed Resource temporarily unavailable
ICECC[25972] 15:44:34: got exception 15 (192.168.0.15)

It's a local network with fairly new computers. I doubt this is the consequence of network instability/hardware problems, but I wouldn't be surprised if this happens because individual machines are running out of memory or something.

Furthermore, this is not specific to any ( set of ) hosts - it seems to happen for all of them at times.

**Comment by llunak** [comment] 2019-07-06 17:01
Duplicate of issue #456 , hopefully fixed.

**Closed by llunak** 2019-07-06 17:01 UTC
