### ISSUE TITLE
Problem running multiple icecc's inside the same network

### ISSUE THREAD

**Issue by PhilippHomann** [icecc/icecream#177] opened 2016-12-02 13:06 UTC
Hi,

first of all I don't know if this is an issue or wanted behaviour.
My scenario:

- One subnet (10.0.0.0/24)
- Two icecc schedulers
-- One for developers
-- One for build environment

For the build-worker/scheduler I've configured
> ICECREAM_SCHEDULER_HOST="build-scheduler"
> ICECREAM_NETNAME="build"

and for the devel-worker/scheduler I've configured
> ICECREAM_SCHEDULER_HOST="devel-scheduler"
> ICECREAM_NETNAME="devel"

When I'm running only one scheduler everthing is fine. The build-worker are connecting to its scheduler and the devel-worker are not able to find one.
When starting the devel-scheduler everything works for some time, but then all worker and clients lose connection to the scheduler.
After putting the devel-scheduler to verbose mode I've found following output:

> Scheduler from 10.0.0.30:46012 (version 34) has announced itself as a preferred scheduler, disconnecting all connections.

So my question is: Is this a expected behaviour?
Why is the scheduler telling the daemons to disconnect if there's another scheduler in the network?
Why aren't the daemons disconnecting and connecting to the other scheduler by themself when they are **not** configured to use a specific scheduler?
Because after some time the devel-worker are reconnecting to the devel-scheduler (because they are told to by configuration) and the whole loop starts again...

Regards

Philipp

**Comment by HenryMiller1** [comment] 2016-12-02 14:48
This is a duplicate of issues #136 and #137.

**Closed by HenryMiller1** 2016-12-02 14:48 UTC

**Comment by HenryMiller1** [comment] 2016-12-02 14:51
In answer to the question, the schedulers are trying to have an election scheme so you can do scheduler failover.  However the netname and clients that are configured to only use that server are not taking into consideration.  This is a bug, but it isn't clear how to fix it.
